/**
 * Mission Control Dashboard — Mock Data
 * 
 * Used for development and testing before real data integration
 */

import type { Agent, RalphLoop, CostData, DailyCost, ActivityItem } from "@/types";

// Mock Agents - The Mission Control Squad
export const mockAgents: Agent[] = [
  {
    id: "klaus",
    name: "klaus",
    display_name: "Klaus",
    emoji: "🎯",
    domain: "Squad Lead",
    description: "Coordinates the agent squad and handles high-level task orchestration",
    soul_path: "agents/klaus/SOUL.md",
    skills: ["coordination", "task-routing", "monitoring"],
    tools: ["sessions_send", "cron", "web_search"],
    status: "online",
    session_key: "agent:klaus:main",
    last_heartbeat: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 min ago
    current_task_id: null,
    heartbeat_schedule: "*/30 * * * *",
    heartbeat_interval_minutes: 30,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "iris",
    name: "iris",
    display_name: "Iris",
    emoji: "📧",
    domain: "Email & Comms",
    description: "Manages email inbox, drafts responses, and handles communications",
    soul_path: "agents/iris/SOUL.md",
    skills: ["email-management", "drafting", "summarization"],
    tools: ["imap", "gmail", "message"],
    status: "online",
    session_key: "agent:iris:main",
    last_heartbeat: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    current_task_id: null,
    heartbeat_schedule: "*/15 * * * *",
    heartbeat_interval_minutes: 15,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "atlas",
    name: "atlas",
    display_name: "Atlas",
    emoji: "📅",
    domain: "Calendar",
    description: "Manages calendar, scheduling, and meeting preparation",
    soul_path: "agents/atlas/SOUL.md",
    skills: ["scheduling", "meeting-prep", "availability"],
    tools: ["google-calendar", "granola"],
    status: "offline",
    session_key: "agent:atlas:main",
    last_heartbeat: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    current_task_id: null,
    heartbeat_schedule: "0 8,12,17 * * *",
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "oracle",
    name: "oracle",
    display_name: "Oracle",
    emoji: "🔮",
    domain: "Intel",
    description: "Gathers intelligence, monitors news, and provides research",
    soul_path: "agents/oracle/SOUL.md",
    skills: ["research", "news-monitoring", "analysis"],
    tools: ["web_search", "web_fetch", "rss"],
    status: "offline",
    session_key: "agent:oracle:main",
    last_heartbeat: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    current_task_id: null,
    heartbeat_schedule: "0 7,13,19 * * *",
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "sentinel",
    name: "sentinel",
    display_name: "Sentinel",
    emoji: "📊",
    domain: "Metrics",
    description: "Tracks metrics, monitors systems, and generates reports",
    soul_path: "agents/sentinel/SOUL.md",
    skills: ["monitoring", "reporting", "alerting"],
    tools: ["supabase", "analytics"],
    status: "offline",
    session_key: "agent:sentinel:main",
    last_heartbeat: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    current_task_id: null,
    heartbeat_schedule: "0 9 * * *",
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "herald",
    name: "herald",
    display_name: "Herald",
    emoji: "📢",
    domain: "Content",
    description: "Creates content, manages social media, and handles publishing",
    soul_path: "agents/herald/SOUL.md",
    skills: ["content-creation", "social-media", "publishing"],
    tools: ["twitter", "linkedin", "blog"],
    status: "offline",
    session_key: "agent:herald:main",
    last_heartbeat: null,
    current_task_id: null,
    heartbeat_schedule: null,
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "forge",
    name: "forge",
    display_name: "Forge",
    emoji: "🔨",
    domain: "Code & PRs",
    description: "Builds code, manages PRs, and handles technical implementation",
    soul_path: "agents/forge/SOUL.md",
    skills: ["coding", "code-review", "debugging"],
    tools: ["github", "exec", "read", "write"],
    status: "busy",
    session_key: "agent:forge:main",
    last_heartbeat: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    current_task_id: "task-mc-dashboard",
    heartbeat_schedule: "10,40 * * * *",
    heartbeat_interval_minutes: 30,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "aegis",
    name: "aegis",
    display_name: "Aegis",
    emoji: "🛡️",
    domain: "Testing",
    description: "Runs tests, validates code, and ensures quality",
    soul_path: "agents/aegis/SOUL.md",
    skills: ["testing", "validation", "qa"],
    tools: ["exec", "github"],
    status: "offline",
    session_key: "agent:aegis:main",
    last_heartbeat: null,
    current_task_id: null,
    heartbeat_schedule: null,
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "codex",
    name: "codex",
    display_name: "Codex",
    emoji: "📚",
    domain: "Docs",
    description: "Maintains documentation, writes guides, and organizes knowledge",
    soul_path: "agents/codex/SOUL.md",
    skills: ["documentation", "writing", "organization"],
    tools: ["notion", "read", "write"],
    status: "offline",
    session_key: "agent:codex:main",
    last_heartbeat: null,
    current_task_id: null,
    heartbeat_schedule: null,
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "pixel",
    name: "pixel",
    display_name: "Pixel",
    emoji: "🎨",
    domain: "UX & Design",
    description: "Creates designs, prototypes, and visual assets",
    soul_path: "agents/pixel/SOUL.md",
    skills: ["design", "prototyping", "visual"],
    tools: ["figma", "image-gen"],
    status: "offline",
    session_key: "agent:pixel:main",
    last_heartbeat: null,
    current_task_id: null,
    heartbeat_schedule: null,
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "pathfinder",
    name: "pathfinder",
    display_name: "Pathfinder",
    emoji: "🧭",
    domain: "Travel",
    description: "Plans travel, researches destinations, and manages itineraries",
    soul_path: "agents/pathfinder/SOUL.md",
    skills: ["travel-planning", "research", "booking"],
    tools: ["web_search", "goplaces"],
    status: "offline",
    session_key: "agent:pathfinder:main",
    last_heartbeat: null,
    current_task_id: null,
    heartbeat_schedule: null,
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "curator",
    name: "curator",
    display_name: "Curator",
    emoji: "🎁",
    domain: "Gifts",
    description: "Finds gifts, tracks occasions, and manages wishlists",
    soul_path: "agents/curator/SOUL.md",
    skills: ["gift-finding", "occasion-tracking", "shopping"],
    tools: ["web_search", "browser"],
    status: "offline",
    session_key: "agent:curator:main",
    last_heartbeat: null,
    current_task_id: null,
    heartbeat_schedule: null,
    heartbeat_interval_minutes: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
];

// Mock Ralph Loops
export const mockRalphLoops: RalphLoop[] = [
  {
    id: "ralph-mc-dashboard",
    buildId: "mission-control-dashboard",
    name: "Mission Control Dashboard Build",
    agent: "forge",
    phase: "build",
    currentStep: 17,
    totalSteps: 48,
    startedAt: "2026-02-02T17:05:00Z",
    lastUpdate: new Date().toISOString(),
    estimatedCompletion: "2026-02-02T23:00:00Z",
    tokensUsed: 45000,
    cost: 2.25,
    output: [
      { timestamp: "2026-02-02T18:45:00Z", type: "success", message: "Created AgentCard.tsx" },
      { timestamp: "2026-02-02T18:43:00Z", type: "success", message: "Set up Tailwind config with design tokens" },
      { timestamp: "2026-02-02T18:40:00Z", type: "success", message: "Initialized Next.js project structure" },
      { timestamp: "2026-02-02T18:38:00Z", type: "info", message: "Reading design specs from specs/..." },
    ],
  },
];

// Mock Cost Data
export const mockCostData: CostData[] = mockAgents.map((agent) => ({
  agentId: agent.id,
  agentName: agent.display_name,
  date: new Date().toISOString().split("T")[0],
  runs: Math.floor(Math.random() * 20),
  inputTokens: Math.floor(Math.random() * 50000),
  outputTokens: Math.floor(Math.random() * 10000),
  totalTokens: 0, // Will be calculated
  cost: 0, // Will be calculated
})).map((data) => ({
  ...data,
  totalTokens: data.inputTokens + data.outputTokens,
  cost: ((data.inputTokens * 0.003 + data.outputTokens * 0.015) / 1000),
}));

// Mock Daily Costs (last 7 days)
export const mockDailyCosts: DailyCost[] = Array.from({ length: 7 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (6 - i));
  const totalCost = 1 + Math.random() * 4;
  return {
    date: date.toISOString().split("T")[0],
    totalCost: Math.round(totalCost * 100) / 100,
    totalTokens: Math.floor(totalCost * 20000),
    byAgent: {
      forge: totalCost * 0.6,
      klaus: totalCost * 0.2,
      iris: totalCost * 0.1,
      atlas: totalCost * 0.05,
      oracle: totalCost * 0.05,
    },
  };
});

// Mock Activity Feed
export const mockActivity: ActivityItem[] = [
  {
    id: "act-1",
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    agentId: "iris",
    agentName: "Iris",
    type: "success",
    message: "Checked inbox — 2 unread flagged",
  },
  {
    id: "act-2",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    agentId: "klaus",
    agentName: "Klaus",
    type: "info",
    message: "Spawned Forge for dashboard build",
  },
  {
    id: "act-3",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    agentId: "atlas",
    agentName: "Atlas",
    type: "info",
    message: "No upcoming meetings in next 2 hours",
  },
  {
    id: "act-4",
    timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    agentId: "sentinel",
    agentName: "Sentinel",
    type: "success",
    message: "Daily metrics baseline captured",
  },
  {
    id: "act-5",
    timestamp: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    agentId: "forge",
    agentName: "Forge",
    type: "info",
    message: "Started Ralph Loop: mission-control-dashboard",
  },
];

// Helper to get agents by status
export function getAgentsByStatus(status: string) {
  return mockAgents.filter((agent) => agent.status === status);
}

// Helper to get agent stats
export function getAgentStats() {
  return {
    total: mockAgents.length,
    online: mockAgents.filter((a) => a.status === "online").length,
    busy: mockAgents.filter((a) => a.status === "busy").length,
    offline: mockAgents.filter((a) => a.status === "offline").length,
    error: mockAgents.filter((a) => a.status === "error").length,
  };
}
